In [84]:
from tensorflow.keras.preprocessing.text import text_to_word_sequence


# 전처리할 텍스트를 정합니다.
text = '해보지 않으면 해낼 수 없다'

# 해당 텍스트를 토큰화합니다.

result = text_to_word_sequence(text)
print('\n원문:\n',text)
print('\n토큰화:\n',result)


원문:
 해보지 않으면 해낼 수 없다

토큰화:
 ['해보지', '않으면', '해낼', '수', '없다']


In [85]:
from tensorflow.keras.preprocessing.text import Tokenizer

docs = ['먼저 텍스트의 각 단어를 나누어 토큰화합니다.',
        '텍스트의 단어로 토크화해야 딥러닝에서 인식됩니다.',
        '토큰화한 결과는 딥러닝에서 사용할 수 있습니다.'
        ]

In [86]:
token = Tokenizer()
token.fit_on_texts(docs) #토큰화 함수에 문장 적용

print('\n단어 카운트:\n', token.word_counts)
print('\n문장 수:\n', token.document_count)
print('\n각 단어가 몇개의 문장에 포함되어 있는지? :\n', token.word_docs)
print('\n각 단어에 매겨진 인덱스 값 :\n', token.word_index)


단어 카운트:
 OrderedDict([('먼저', 1), ('텍스트의', 2), ('각', 1), ('단어를', 1), ('나누어', 1), ('토큰화합니다', 1), ('단어로', 1), ('토크화해야', 1), ('딥러닝에서', 2), ('인식됩니다', 1), ('토큰화한', 1), ('결과는', 1), ('사용할', 1), ('수', 1), ('있습니다', 1)])

문장 수:
 3

각 단어가 몇개의 문장에 포함되어 있는지? :
 defaultdict(<class 'int'>, {'먼저': 1, '나누어': 1, '단어를': 1, '텍스트의': 2, '각': 1, '토큰화합니다': 1, '인식됩니다': 1, '토크화해야': 1, '딥러닝에서': 2, '단어로': 1, '사용할': 1, '토큰화한': 1, '있습니다': 1, '수': 1, '결과는': 1})

각 단어에 매겨진 인덱스 값 :
 {'텍스트의': 1, '딥러닝에서': 2, '먼저': 3, '각': 4, '단어를': 5, '나누어': 6, '토큰화합니다': 7, '단어로': 8, '토크화해야': 9, '인식됩니다': 10, '토큰화한': 11, '결과는': 12, '사용할': 13, '수': 14, '있습니다': 15}


#### 2. 단어의 원-핫 인코딩

In [87]:
text = "오랫동안 꿈꾸는 이는 그 꿈을 닮아간다"

token = Tokenizer()
token.fit_on_texts([text])
print(token.word_index)

x = token.texts_to_sequences([text])
print(x)

{'오랫동안': 1, '꿈꾸는': 2, '이는': 3, '그': 4, '꿈을': 5, '닮아간다': 6}
[[1, 2, 3, 4, 5, 6]]


In [88]:
from tensorflow.keras.utils import to_categorical

#인덱스 수에 하나를 추가해서 원-핫 인코딩 배열 만들기
word_size = len(token.word_index) +1 #배열 맨 앞에 0이 추가되므로 단어 수보다 1이 더 많게 인덱스 숫자를 잡아줘야함

x = to_categorical(x, num_classes = word_size)

print(x)

[[[0. 1. 0. 0. 0. 0. 0.]
  [0. 0. 1. 0. 0. 0. 0.]
  [0. 0. 0. 1. 0. 0. 0.]
  [0. 0. 0. 0. 1. 0. 0.]
  [0. 0. 0. 0. 0. 1. 0.]
  [0. 0. 0. 0. 0. 0. 1.]]]


#### 3. 단어 임베딩

In [89]:
# 원-핫 인코딩을 그대로 사용하면 벡터의 길이가 너무 길어진다는 단점
# 단어 유사도를 비교하여 적절한 배열만듦
from tensorflow.keras.layers import Embedding
from tensorflow.keras.models import Sequential

model = Sequential()
model.add(Embedding(16,4, input_length = 2)) #input_length는 패딩한 길이, 4는 임의로 줬지만 보통 2배?

#### 4. 텍스트를 읽고 긍정, 부정 예측

In [90]:
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Flatten, Embedding
from tensorflow.keras.utils import to_categorical

from numpy import array

In [91]:
#텍스트 리뷰 자료를 지정
reviews = ['너무 재밌네요', '최고예요', '참 잘 만든 영화예요', '추천하고 싶은 영화입니다', '한번 더 보고싶네요', '글쎄요', '별로예요', '생각보다 지루하네요', '연기가 어색해요','재미없어요']

#긍정 리뷰는 1, 부정 리뷰는 0으로 클래스를 지정
classes = array([1,1,1,1,1,0,0,0,0,0])

In [92]:
#토큰화
token = Tokenizer()
token.fit_on_texts(reviews)
print(token.word_index)

x = token.texts_to_sequences(reviews)
print('\n리뷰 텍스트, 토큰화 결과:\n',x)

{'너무': 1, '재밌네요': 2, '최고예요': 3, '참': 4, '잘': 5, '만든': 6, '영화예요': 7, '추천하고': 8, '싶은': 9, '영화입니다': 10, '한번': 11, '더': 12, '보고싶네요': 13, '글쎄요': 14, '별로예요': 15, '생각보다': 16, '지루하네요': 17, '연기가': 18, '어색해요': 19, '재미없어요': 20}

리뷰 텍스트, 토큰화 결과:
 [[1, 2], [3], [4, 5, 6, 7], [8, 9, 10], [11, 12, 13], [14], [15], [16, 17], [18, 19], [20]]


In [93]:
#패딩, 서로 다른 길이의 데이터를 4로 맞춤
padded_x = pad_sequences(x,4)
print('\n패딩 결과:\n', padded_x)


패딩 결과:
 [[ 0  0  1  2]
 [ 0  0  0  3]
 [ 4  5  6  7]
 [ 0  8  9 10]
 [ 0 11 12 13]
 [ 0  0  0 14]
 [ 0  0  0 15]
 [ 0  0 16 17]
 [ 0  0 18 19]
 [ 0  0  0 20]]


In [94]:
#임베딩에 입력될 단어의 수를 지정
word_size = len(token.word_index)+1

In [95]:
#단어 임베딩을 포함해 딥러닝 모델 만들고 결과 출력
model = Sequential()
model.add(Embedding(word_size, 8, input_length=4))
model.add(Flatten())
model.add(Dense(1, activation = 'sigmoid')) #긍정 부정 이진분류
model.summary()

Model: "sequential_14"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_14 (Embedding)    (None, 4, 8)              168       
                                                                 
 flatten_6 (Flatten)         (None, 32)                0         
                                                                 
 dense_6 (Dense)             (None, 1)                 33        
                                                                 
Total params: 201
Trainable params: 201
Non-trainable params: 0
_________________________________________________________________


In [96]:
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])
model.fit(padded_x, classes, epochs=20)
print('\nAccuracy: %.4f' %(model.evaluate(padded_x,classes)[1]))

Epoch 1/20


1/1 [==============================] - 1s 554ms/step - loss: 0.6980 - accuracy: 0.4000
Epoch 2/20
1/1 [==============================] - 0s 7ms/step - loss: 0.6960 - accuracy: 0.4000
Epoch 3/20
1/1 [==============================] - 0s 6ms/step - loss: 0.6941 - accuracy: 0.4000
Epoch 4/20
1/1 [==============================] - 0s 6ms/step - loss: 0.6922 - accuracy: 0.5000
Epoch 5/20
1/1 [==============================] - 0s 5ms/step - loss: 0.6903 - accuracy: 0.7000
Epoch 6/20
1/1 [==============================] - 0s 7ms/step - loss: 0.6884 - accuracy: 0.7000
Epoch 7/20
1/1 [==============================] - 0s 7ms/step - loss: 0.6865 - accuracy: 0.9000
Epoch 8/20
1/1 [==============================] - 0s 7ms/step - loss: 0.6846 - accuracy: 0.9000
Epoch 9/20
1/1 [==============================] - 0s 6ms/step - loss: 0.6828 - accuracy: 1.0000
Epoch 10/20
1/1 [==============================] - 0s 6ms/step - loss: 0.6809 - accuracy: 1.0000
Epoch 11/20
1/1 [==============================]